apiVersion: v1
entries:
  csi-powerstore:
  - apiVersion: v2
    appVersion: 2.4.0
    created: "2022-11-15T02:46:58.767379462-05:00"
    dependencies:
    - condition: csm-application-mobility.enabled
      name: csm-application-mobility
      repository: https://chaganti-rajitha.github.io/csm-installation/charts/pkg/
      version: 0.1.0
    - condition: karavi-observability.enabled
      name: karavi-observability
      repository: https://chaganti-rajitha.github.io/csm-installation/charts/pkg/
      version: 1.3.1
    - condition: csm-replication.enabled
      name: csm-replication
      repository: https://chaganti-rajitha.github.io/csm-installation/charts/pkg/
      version: 1.3.0
    description: 'PowerStore CSI (Container Storage Interface) driver Kubernetes integration.
      This chart includes everything required to provision via CSI as well as a PowerStore
      StorageClass. '
    digest: d58db79b2f37a6a606ab4238e5d7026a690f0e8d5b3f60b0c87aa599ad3efebe
    home: https://github.com/dell/csi-powerstore
    keywords:
    - csi
    - storage
    kubeVersion: '>= 1.21.0 < 1.26.0'
    maintainers:
    - name: DellEMC
    name: csi-powerstore
    sources:
    - https://github.com/dell/csi-powerstore
    urls:
    - csi-powerstore-2.4.0.tgz
    version: 2.4.0
  csm-application-mobility:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-11-15T02:46:58.77456241-05:00"
    dependencies:
    - condition: cert-manager.enabled
      name: cert-manager
      repository: https://charts.jetstack.io
      version: 1.8.2
    - condition: velero.enabled
      name: velero
      repository: https://vmware-tanzu.github.io/helm-charts
      version: 2.29.8
    description: A Helm chart deploying Application Mobility
    digest: 9af203a9d1df18598b7242c411d27505c4dbd6f7bf3854737bc16a44cd0e7534
    name: csm-application-mobility
    type: application
    urls:
    - csm-application-mobility-0.1.0.tgz
    version: 0.1.0
  csm-replication:
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2022-11-15T02:46:58.774896301-05:00"
    description: A Helm chart deploying Replication
    digest: 3551b9f57c844f96ed9cab4db5e454ea022dbdc3dff50ddeb929a2e57705fb61
    name: csm-replication
    type: application
    urls:
    - csm-replication-1.3.0.tgz
    version: 1.3.0
  karavi-observability:
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2022-11-15T02:46:58.791457977-05:00"
    dependencies:
    - name: cert-manager
      repository: https://charts.jetstack.io
      version: 1.6.1
    description: CSM for Observability is part of the [Container Storage Modules](https://github.com/dell/csm)
      open source suite of Kubernetes storage enablers for Dell EMC storage products.
      CSM for Observability provides Kubernetes administrators with visibility into
      metrics and topology data related to containerized storage.
    digest: c873710a7f2ed332a7e7f5cb1a312dc0cfed812a7be76abfd4063f189a20f635
    name: karavi-observability
    type: application
    urls:
    - karavi-observability-1.3.1.tgz
    version: 1.3.1
generated: "2022-11-15T02:46:58.738277845-05:00"
