apiVersion: v1
entries:
  csi-powerstore:
  - apiVersion: v2
    appVersion: 2.4.0
    created: "2022-10-20T01:02:22.960851994-04:00"
    description: 'PowerStore CSI (Container Storage Interface) driver Kubernetes integration.
      This chart includes everything required to provision via CSI as well as a PowerStore
      StorageClass. '
    digest: 4cabb3c4bd5ba8c1346b871d1fefdddd82ce2c7887629fe97f85b8f0815f760c
    home: https://github.com/dell/csi-powerstore
    keywords:
    - csi
    - storage
    kubeVersion: '>= 1.21.0 < 1.26.0'
    maintainers:
    - name: DellEMC
    name: csi-powerstore
    sources:
    - https://github.com/dell/csi-powerstore
    urls:
    - csi-powerstore-2.4.0.tgz
    version: 2.4.0
generated: "2022-10-20T01:02:22.958967542-04:00"
