name: csi-powerstore
apiVersion: v2
version: 2.6.0
appVersion: "2.6.0"
kubeVersion: ">= 1.21.0 < 1.26.0"
#If you are using a complex K8s version like "v1.22.3-mirantis-1", use this kubeVersion check instead
#WARNING: this version of the check will allow the use of alpha and beta versions, which is NOT SUPPORTED
#kubeVersion: ">= 1.21.0-0 < 1.26.0-0"
description: |
  PowerStore CSI (Container Storage Interface) driver Kubernetes
  integration. This chart includes everything required to provision via CSI as
  well as a PowerStore StorageClass.
keywords:
- csi
- storage
home: https://github.com/dell/csi-powerstore
sources:
- https://github.com/dell/csi-powerstore
maintainers:
- name: DellEMC
dependencies:
- name: csm-application-mobility
  version: 0.1.0
  repository: https://chaganti-rajitha.github.io/csm-installation/charts/pkg/
  condition: csm-application-mobility.enabled

- name: karavi-observability
  version: 1.3.1
  repository: https://chaganti-rajitha.github.io/csm-installation/charts/pkg/
  condition: karavi-observability.enabled
  
- name: csm-replication
  version: 1.3.0
  repository: https://chaganti-rajitha.github.io/csm-installation/charts/pkg/
  condition: csm-replication.enabled

